## Do not edit this file unless either
##  A: You know what you are doing
##  B: You want to break this program

import os

CONFIG_FILE_PATH = os.path.join(
        os.path.expanduser("~"),
        ".local",
        "share",
        "smuxi",
        "np-config.yml",
        )
REQUIRED_OPTIONS = {"player", "format"}
COLORS = {
        u"b": "\x02", ## BOLD
        }
SOCKET_TIMEOUT = 0.01
